name: geoff
description: A library of common code used in our projects
version: 0.1.8-testing-1

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_appauth: ^2.4.1
  grpc: ^3.0.2
  http: ^0.13.4
  jaguar_jwt: ^3.0.0
  native_device_orientation: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  


flutter:
  