name: geoff
description: A library of common code used in our projects
version: 0.2.10
repository: https://github.com/Kibibibit/geoff
documentation: https://github.com/Kibibibit/geoff/wiki

environment:
  sdk: ">=3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_appauth: ^4.2.0
  grpc: ^3.0.2
  http: ^1.0.0
  jaguar_jwt: ^3.0.0
  native_device_orientation: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  


flutter:
  